```javascript
import ConnectError from '@endpass/connect/ConnectError';

const scopes = [
  'user:email:read',
  'user:phone:read',
];

const requestParams = {
  url: 'https://api.endpass.com/v1/user',
  method: 'GET',
  // Also you can pass scopes to the instance
  scopes,
};

// async / await
(async () => {
  try {
    // Fetch required data
    const userInfo = await connect.request(requestParams);
  } catch(e) {
    // You can match the type of error from the imported instance
    if (e.code === ConnectError.ERRORS.AUTH) {
      handleError();
    }

    // Or Connect/Plugin instance
    if (e.code === connect.ERRORS.AUTH) {
      handleError();
    }

    console.log(e);
  }
})();
```

> Suppose an error has been thrown and can be seen in the console

```json
{
  "message": "Some error message",
  "code": "CODE_FROM_ERRORS_SECTION",
  // ...other props from Error instance
}
```